version: "3"
services: 
    tomcat:
        container_name: tomcat
        build: ./tomcat-8.5
        ports:
            - 8080:8080
        volumes:
            - ./webapps:/usr/local/tomcat/webapps